version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: property_postgres
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: property_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
